[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.0"
license = "MIT"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
floretta = { path = "crates/floretta" }
wasm-encoder = "0.220"
wasmparser = "0.220"
wasmprinter = "0.220"
wat = "1"
