[package]
name = "floretta"
description = "Automatic differentiation for WebAssembly."
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
wasm-encoder.workspace = true
wasmparser.workspace = true
