name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test

  cli:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.target }}
          args: --release --package floretta-cli
      - uses: actions/upload-artifact@v4
        with:
          name: floretta-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/floretta

  wasm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: .github/wasm.py -o $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: floretta.wasm
