name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo test
      - run: cargo build --package=floretta-wasm --target=wasm32-unknown-unknown --release
      - uses: actions/upload-artifact@v4
        with:
          name: floretta.wasm
          path: target/wasm32-unknown-unknown/release/floretta_wasm.wasm
