name: Release
on:
  release:
    types:
      - created

jobs:
  crate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --package floretta
      - env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --package floretta-cli

  cli:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.target }}
          args: --release --package floretta-cli
      - run: cp target/${{ matrix.target }}/release/floretta floretta-${{ matrix.target }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} floretta-${{ matrix.target }}
